import React from "react";
import { Nav, TeachingBubble, Icon, Label } from "@fluentui/react";
import { useDropzone } from "react-dropzone";
import "./Menu.css";
import { useService } from "use-service";

const HELP_KEY = 'har-editor-help';

function download(filename, text) {
  var element = document.createElement('a');
  element.setAttribute('href', 'data:application/json;charset=utf-8,' + encodeURIComponent(text));
  element.setAttribute('download', filename);

  element.style.display = 'none';
  document.body.appendChild(element);

  element.click();

  document.body.removeChild(element);
}

export function Menu(props) {
  const $har = useService("$har");
  const [uploadEl, setEl] = React.useState();
  const [hideHelp, setHideHelp] = React.useState(localStorage.getItem(HELP_KEY));
  const dismissHelp = () => {
    localStorage.setItem(HELP_KEY, 'true');
    setHideHelp(true);
  }

  const onDrop = React.useCallback((acceptedFiles) => {
    $har.addFiles(acceptedFiles);
  }, [$har]);

  const { getRootProps, getInputProps } = useDropzone({ onDrop });

  const exportedHAR = $har.export();
  const actions = {
    name: 'Actions',
    links: [],
  };
  const hars = {
    name: "HARs",
    initialSelectedKey: $har.current && $har.current.name,
    links: $har.files.map(f => {
      const res = {
        key: f.name,
        name: f.name,
        url: '',
        onClick: () => $har.select(f)
      };
      return res;
    })
  };
  const hasHARs = hars.links.length > 0;
  if (hasHARs) {
    actions.links.push({
      key: 'export',
      name: 'Export',
      url: '',
      onClick: () => {
        var content = JSON.stringify(exportedHAR);
        const filename = `har-editor-export-${Date.now()}.har`;
        download(filename, content);
      },
      icon: 'Download',
    });
  }
  const navgroups = [
    hars,
    actions,
  ];

  const examplePrimaryButton = {
    children: 'OK got it',
    onClick: dismissHelp
  };
  const exampleSecondaryButtonProps = {
    children: 'Learn more',
    href: 'http://www.softwareishard.com/blog/har-12-spec/',
  };
  const [collapsed, setCollapsed] = React.useState(false);

  return (
    <div className={`menu flex${collapsed ? ' collapsed' : ''}`}>
      <button className="menu-toggle" onClick={() => setCollapsed(c => !c)} title={collapsed ? "Expand sidebar" : "Collapse sidebar"}>
        <Icon iconName={collapsed ? "ChevronRight" : "ChevronLeft"} />
      </button>
      <div className="menu-content">
        <Nav styles={{ root: { width: 200 } }} groups={navgroups} />
        <section className="upload" ref={setEl}>
          <div {...getRootProps()} className="upload-wrapper">
            <Label required htmlFor="upload-har">Upload</Label>
            <input {...getInputProps()} id="upload-har" />
            <Icon className="ms-Icon" iconName="Upload" />
          </div>
        </section>
      </div>
      {uploadEl && !hideHelp && <TeachingBubble
          target={uploadEl}
          primaryButtonProps={examplePrimaryButton}
          secondaryButtonProps={exampleSecondaryButtonProps}
          onDismiss={() => dismissHelp()}
          headline="You can drag and drop HAR file here"
        >
          HAR files are generated by devtools in network tabs.
      </TeachingBubble>}
    </div>
  );
}
